# Generated by Django 5.2.3 on 2025-07-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit',
        ),
    ]
